# Generated by Django 5.0.3 on 2024-03-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
