# Generated by Django 5.0.3 on 2024-03-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0002_client_email_client_first_name_client_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.AddField(
            model_name='client',
            name='auto_create_schema',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
    ]
