# Generated by Django 5.0.3 on 2024-03-14 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0003_remove_client_email_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=False, max_length=100)),
                ('last_name', models.CharField(default=False, max_length=100)),
                ('email', models.CharField(default=False, max_length=100)),
                ('password', models.CharField(default=False, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='global_app.client')),
            ],
        ),
    ]
