# Generated by Django 5.0.3 on 2024-03-14 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0004_alter_client_name_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
