# Generated by Django 5.0.3 on 2024-03-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0006_userprofile_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='auto_create_schema',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
